### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by sungjuly** [listia/samson_hipchat#1]
Hi folks,

Thank you for building useful plugin ;) I just want to let you know that I've experienced error. In my case, I just changed message template.
# Versions

samson version : https://github.com/zendesk/samson/tree/2538360c43ccdfba479dfba1e62c48d3d5c43701
samson_hipchat version: https://github.com/listia/samson_hipchat/tree/5a9c3b99a9ef7908080dccf24e7c3467fe3dc4b9
# Error

NoMethodError in Deploys#create
Showing /samson/plugins/hipchat/app/views/samson_hipchat/notification.text.erb where line #2 raised:
- https://github.com/listia/samson_hipchat/blob/master/app/views/samson_hipchat/notification.text.erb#L2

undefined method `message' for #Deploy:0x00000004d3af50
Extracted source (around line #119):

```
    # use
      def fire(name, *args)
        hooks(name).map { |hook| hook.call(*args) } < -here
      end

      def render_views(name, view, *args)
```
# Full stack

```
activemodel (4.2.3) lib/active_model/attribute_methods.rb:433:in `method_missing'
plugins/hipchat/app/views/samson_hipchat/notification.text.erb:2:in `_plugins_hipchat_app_views_samson_hipchat_notification_text_erb__650577229518029664_36188140'
actionview (4.2.3) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.3) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.3) lib/action_view/template.rb:143:in `render'
rack-mini-profiler (0.9.3) lib/mini_profiler/profiling_methods.rb:106:in `block in profile_method'
actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.3) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.2.3) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.2.3) lib/action_view/helpers/rendering_helper.rb:32:in `render'
plugins/hipchat/app/models/hipchat_notification_renderer.rb:6:in `render'
plugins/hipchat/app/models/hipchat_notification.rb:57:in `content'
plugins/hipchat/app/models/hipchat_notification.rb:52:in `to_s'
plugins/hipchat/app/models/hipchat_notification.rb:11:in `deliver'
plugins/hipchat/lib/samson_hipchat/samson_plugin.rb:17:in `block in <top (required)>'
lib/samson/hooks.rb:119:in `call'
lib/samson/hooks.rb:119:in `block in fire'
lib/samson/hooks.rb:119:in `map'
lib/samson/hooks.rb:119:in `fire'
app/models/deploy_service.rb:57:in `send_before_notifications'
app/models/deploy_service.rb:20:in `confirm_deploy!'
app/models/deploy_service.rb:13:in `deploy!'
app/controllers/deploys_controller.rb:44:in `create'
actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
rack-mini-profiler (0.9.3) lib/mini_profiler/profiling_methods.rb:106:in `block in profile_method'
actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `call'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
better_errors (2.1.1) lib/better_errors/middleware.rb:59:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
rack-mini-profiler (0.9.3) lib/mini_profiler/profiler.rb:276:in `call'
railties (4.2.3) lib/rails/engine.rb:518:in `call'
railties (4.2.3) lib/rails/application.rb:165:in `call'
puma (2.11.3) lib/puma/rack_patch.rb:13:in `call'
puma (2.11.3) lib/puma/configuration.rb:51:in `call'
puma (2.11.3) lib/puma/server.rb:507:in `handle_request'
puma (2.11.3) lib/puma/server.rb:375:in `process_client'
puma (2.11.3) lib/puma/server.rb:262:in `block in run'
puma (2.11.3) lib/puma/thread_pool.rb:104:in `call'
puma (2.11.3) lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by v9n** [comment]
@sungjuly Hi,

My bad. I thought you forgot to run `migration` because we add a new column `message` on `deploy` table. Turning it that migration was in our private plugin. This hipchat plugin depends on our private plugin to include a custom message.

I just deploy a fix to fix it. https://github.com/listia/samson_hipchat/commit/b66400082a4700fedb3bb4764993a5987c384118
Thanks for reporting.
